In [1]:
import requests
import pandas as pd
import numpy as np
import datetime
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
def getBoosterVersion(data):
    for x in data['rocket']:
        if x:
            response = requests.get("https://api.spacexdata.com/v4/rockets/"+str(x)).json()
            BoosterVersion.append(response['name'])

In [2]:
static_json_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json"

response = requests.get(static_json_url)

print(response.status_code)

200

In [8]:
data = pd.json_normalize(response.json())

In [4]:
data.shape

(107, 42)

In [9]:
data = data[['rocket', 'payloads', 'launchpad', 'flight_number', 'cores', 'date_utc']]

In [10]:
data = data[data['cores'].map(len)==1]
data = data[data['payloads'].map(len)==1]

In [11]:
data['cores'] = data['cores'].map(lambda x: x[0])
data['payloads'] = data['payloads'].map(lambda x: x[0])

In [16]:
data['date'] = pd.to_datetime(data['date_utc']).dt.date

In [18]:
data = data[data['date'] <= datetime.date(2020, 11, 13)]

In [19]:
data.shape

(94, 7)

In [21]:
# Static rocket reference data
rocket_data = [
    {"id": "5e9d0d95eda69955f709d1eb", "name": "Falcon 1"},
    {"id": "5e9d0d95eda69973a809d1ec", "name": "Falcon 9"},
    {"id": "5e9d0d95eda69974db09d1ed", "name": "Falcon Heavy"}
]

rocket_lookup = {
    rocket["id"]: rocket["name"]
    for rocket in rocket_data
}

In [22]:
rocket_lookup["5e9d0d95eda69973a809d1ec"]

'Falcon 9'

In [23]:
def getBoosterVersion(data):
    for x in data['rocket']:
        if x:
            BoosterVersion.append(rocket_lookup.get(x))

In [26]:
BoosterVersion = []

In [28]:
getBoosterVersion(data)

In [29]:
BoosterVersion[:10]

['Falcon 1',
 'Falcon 1',
 'Falcon 1',
 'Falcon 1',
 'Falcon 1',
 'Falcon 9',
 'Falcon 9',
 'Falcon 9',
 'Falcon 9',
 'Falcon 9']

In [3]:
def getLaunchSite(data):
    for x in data['launchpad']:
        if x:
            response = requests.get("https://api.spacexdata.com/v4/launchpads"+str(x)).json()
            Longitude.append(response['longitude'])
            Latitude.append(reponse['latitude'])
            LaunchSite.append(response['name'])

In [33]:
def getLaunchSite(data):
    for x in data['launchpad']:
        if x:
            launchpad = launchpad_lookup.get(x)

            Longitude.append(launchpad['longitude'])
            Latitude.append(launchpad['latitude'])
            LaunchSite.append(launchpad['name'])

In [34]:
Longitude = []
Latitude = []
LaunchSite = []

In [35]:
getLaunchSite(data)

In [36]:
LaunchSite[:10]

['Kwajalein Atoll',
 'Kwajalein Atoll',
 'Kwajalein Atoll',
 'Kwajalein Atoll',
 'Kwajalein Atoll',
 'CCSFS SLC 40',
 'CCSFS SLC 40',
 'CCSFS SLC 40',
 'CCSFS SLC 40',
 'CCSFS SLC 40']

In [37]:
print(len(data))
print(len(LaunchSite))
print(len(Longitude))
print(len(Latitude))

107
107
107
107

In [5]:
#def getPayloadData(data):
    #for load in data['payloads']:
        #if load:
            #response = requests.get("https://api.spacexdata.com/v4/payloads"+load).json()
            #PayloadMass.append(response['mass_kg'])
            #Orbit.append(response['orbit'])

In [49]:
def getPayloadData(data):
    for date in data['date']:
        if date in payload_lookup:
            PayloadMass.append(payload_lookup[date]['PayloadMass'])
            Orbit.append(payload_lookup[date]['Orbit'])
        else:
            PayloadMass.append(None)
            Orbit.append(None)

In [52]:
data.columns.tolist()

['static_fire_date_utc',
 'static_fire_date_unix',
 'tbd',
 'net',
 'window',
 'rocket',
 'success',
 'details',
 'crew',
 'ships',
 'capsules',
 'payloads',
 'launchpad',
 'auto_update',
 'failures',
 'flight_number',
 'name',
 'date_utc',
 'date_unix',
 'date_local',
 'date_precision',
 'upcoming',
 'cores',
 'id',
 'fairings.reused',
 'fairings.recovery_attempt',
 'fairings.recovered',
 'fairings.ships',
 'links.patch.small',
 'links.patch.large',
 'links.reddit.campaign',
 'links.reddit.launch',
 'links.reddit.media',
 'links.reddit.recovery',
 'links.flickr.small',
 'links.flickr.original',
 'links.presskit',
 'links.webcast',
 'links.youtube_id',
 'links.article',
 'links.wikipedia',
 'fairings']

In [53]:
data['date'] = pd.to_datetime(data['date_utc']).dt.date

In [54]:
data[['date_utc', 'date']].head()

                   date_utc        date
0  2006-03-24T22:30:00.000Z  2006-03-24
1  2007-03-21T01:10:00.000Z  2007-03-21
2  2008-08-03T03:34:00.000Z  2008-08-03
3  2008-09-28T23:15:00.000Z  2008-09-28
4  2009-07-13T03:35:00.000Z  2009-07-13

In [59]:
PayloadMass = []
Orbit = []

In [60]:
getPayloadData(data)

In [61]:
print(len(data))
print(len(PayloadMass))
print(len(Orbit))

107
107
107

In [41]:
payload_ids = data['payloads'].explode().unique()

In [42]:
len(payload_ids)

132

In [43]:
payload_ids[:10]

array(['5eb0e4b5b6c3bb0006eeb1e1', '5eb0e4b6b6c3bb0006eeb1e2',
       '5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb0006eeb1e4',
       '5eb0e4b7b6c3bb0006eeb1e5', '5eb0e4b7b6c3bb0006eeb1e6',
       '5eb0e4b7b6c3bb0006eeb1e7', '5eb0e4b9b6c3bb0006eeb1e8',
       '5eb0e4b9b6c3bb0006eeb1e9', '5eb0e4bab6c3bb0006eeb1ea'],
      dtype=object)

In [30]:
data['launchpad'].unique()

array(['5e9e4502f5090995de566f86', '5e9e4501f509094ba4566f84',
       '5e9e4502f509092b78566f87', '5e9e4502f509094188566f88'],
      dtype=object)

In [20]:
fallback_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv"

fallback = pd.read_csv(fallback_url)

fallback.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

In [45]:
fallback.shape

(90, 17)

In [46]:
fallback['Date'] = pd.to_datetime(fallback['Date']).dt.date

print("Fallback rows:", len(fallback))
print("Unique fallback dates:", fallback['Date'].nunique())

Fallback rows: 90
Unique fallback dates: 90

In [62]:
fallback.columns.tolist()

['FlightNumber',
 'Date',
 'BoosterVersion',
 'PayloadMass',
 'Orbit',
 'LaunchSite',
 'Outcome',
 'Flights',
 'GridFins',
 'Reused',
 'Legs',
 'LandingPad',
 'Block',
 'ReusedCount',
 'Serial',
 'Longitude',
 'Latitude']

In [21]:
payload_lookup = fallback.set_index('Date')[['PayloadMass', 'Orbit']].to_dict('index')

In [24]:
core_lookup = fallback.set_index('Date')[
    ['Outcome', 'Flights', 'GridFins', 'Reused', 'Legs',
     'LandingPad', 'Block', 'ReusedCount', 'Serial']
].to_dict('index')

In [25]:
print(len(payload_lookup))
print(len(core_lookup))

90
90

In [26]:
PayloadMass = []
Orbit = []

Outcome = []
Flights = []
GridFins = []
Reused = []
Legs = []
LandingPad = []
Block = []
ReusedCount = []
Serial = []

for date in data['date']:

    if date in payload_lookup:
        PayloadMass.append(payload_lookup[date]['PayloadMass'])
        Orbit.append(payload_lookup[date]['Orbit'])
    else:
        PayloadMass.append(None)
        Orbit.append(None)

    if date in core_lookup:
        core = core_lookup[date]

        Outcome.append(core['Outcome'])
        Flights.append(core['Flights'])
        GridFins.append(core['GridFins'])
        Reused.append(core['Reused'])
        Legs.append(core['Legs'])
        LandingPad.append(core['LandingPad'])
        Block.append(core['Block'])
        ReusedCount.append(core['ReusedCount'])
        Serial.append(core['Serial'])
    else:
        Outcome.append(None)
        Flights.append(None)
        GridFins.append(None)
        Reused.append(None)
        Legs.append(None)
        LandingPad.append(None)
        Block.append(None)
        ReusedCount.append(None)
        Serial.append(None)

In [27]:
print(len(data))
print(len(PayloadMass))
print(len(Orbit))
print(len(Outcome))
print(len(Flights))
print(len(GridFins))
print(len(Reused))
print(len(Legs))
print(len(LandingPad))
print(len(Block))
print(len(ReusedCount))
print(len(Serial))

94
94
94
94
94
94
94
94
94
94
94
94

In [28]:
rocket_lookup = {
    "5e9d0d95eda69955f709d1eb": "Falcon 1",
    "5e9d0d95eda69973a809d1ec": "Falcon 9",
    "5e9d0d95eda69974db09d1ed": "Falcon Heavy"
}

launchpad_lookup = {
    "5e9e4502f5090995de566f86": {
        "name": "Kwajalein Atoll",
        "latitude": 9.0477206,
        "longitude": 167.7431292
    },
    "5e9e4501f509094ba4566f84": {
        "name": "CCSFS SLC 40",
        "latitude": 28.5618571,
        "longitude": -80.577366
    },
    "5e9e4502f509092b78566f87": {
        "name": "VAFB SLC 4E",
        "latitude": 34.632093,
        "longitude": -120.610829
    },
    "5e9e4502f509094188566f88": {
        "name": "KSC LC 39A",
        "latitude": 28.6080585,
        "longitude": -80.6039558
    }
}

In [29]:
BoosterVersion = []
LaunchSite = []
Longitude = []
Latitude = []

for rocket_id, launchpad_id in zip(data['rocket'], data['launchpad']):

    BoosterVersion.append(rocket_lookup.get(rocket_id))

    site = launchpad_lookup.get(launchpad_id)

    if site:
        LaunchSite.append(site['name'])
        Longitude.append(site['longitude'])
        Latitude.append(site['latitude'])
    else:
        LaunchSite.append(None)
        Longitude.append(None)
        Latitude.append(None)

In [30]:
print(len(data))
print(len(BoosterVersion))
print(len(LaunchSite))
print(len(Longitude))
print(len(Latitude))

94
94
94
94
94

In [31]:
launch_dict = {
    'FlightNumber': list(data['flight_number']),
    'Date': list(data['date']),
    'BoosterVersion': BoosterVersion,
    'PayloadMass': PayloadMass,
    'Orbit': Orbit,
    'LaunchSite': LaunchSite,
    'Outcome': Outcome,
    'Flights': Flights,
    'GridFins': GridFins,
    'Reused': Reused,
    'Legs': Legs,
    'LandingPad': LandingPad,
    'Block': Block,
    'ReusedCount': ReusedCount,
    'Serial': Serial,
    'Longitude': Longitude,
    'Latitude': Latitude
}

In [32]:
data_falcon9 = pd.DataFrame(launch_dict)
data_falcon9.shape

(94, 17)

In [33]:
data = pd.DataFrame(launch_dict) #Task 1

In [34]:
data.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2006-03-24,Falcon 1,None,None,Kwajalein Atoll,None,None,None,None,None,None,None,None,None,167.743129,9.047721
1,2,2007-03-21,Falcon 1,None,None,Kwajalein Atoll,None,None,None,None,None,None,None,None,None,167.743129,9.047721
2,4,2008-09-28,Falcon 1,None,None,Kwajalein Atoll,None,None,None,None,None,None,None,None,None,167.743129,9.047721
3,5,2009-07-13,Falcon 1,None,None,Kwajalein Atoll,None,None,None,None,None,None,None,None,None,167.743129,9.047721
4,6,2010-06-04,Falcon 9,None,None,CCSFS SLC 40,None,None,None,None,None,None,None,None,None,-80.577366,28.561857

In [37]:
#Task 2 filtering
data_falcon9 = data[data['BoosterVersion'] != 'Falcon 1'].copy()

In [38]:
data_falcon9.loc[:, 'FlightNumber'] = list(range(1, data_falcon9.shape[0] + 1))

In [39]:
data_falcon9.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
4,1,2010-06-04,Falcon 9,None,None,CCSFS SLC 40,None,None,None,None,None,None,None,None,None,-80.577366,28.561857
5,2,2012-05-22,Falcon 9,None,None,CCSFS SLC 40,None,None,None,None,None,None,None,None,None,-80.577366,28.561857
6,3,2013-03-01,Falcon 9,None,None,CCSFS SLC 40,None,None,None,None,None,None,None,None,None,-80.577366,28.561857
7,4,2013-09-29,Falcon 9,None,None,VAFB SLC 4E,None,None,None,None,None,None,None,None,None,-120.610829,34.632093
8,5,2013-12-03,Falcon 9,None,None,CCSFS SLC 40,None,None,None,None,None,None,None,None,None,-80.577366,28.561857

In [40]:
data_falcon9 = fallback.copy()

In [41]:
data_falcon9.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

In [42]:
data_falcon9.isnull().sum() / len(data_falcon9) * 100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

In [43]:
data_falcon9.to_csv('dataset_part_1.csv', index=False)

In [44]:
!ls

dataset_part_1.csv			       spacex_data_collection-api.ipynb
jupyter-labs-spacex-data-collection-api.ipynb

In [48]:
list(payload_lookup.items())[:3]

[(datetime.date(2010, 6, 4),
  {'PayloadMass': 6104.959411764706, 'Orbit': 'LEO'}),
 (datetime.date(2012, 5, 22), {'PayloadMass': 525.0, 'Orbit': 'LEO'}),
 (datetime.date(2013, 3, 1), {'PayloadMass': 677.0, 'Orbit': 'ISS'})]

In [31]:
launchpad_lookup = {
    "5e9e4502f5090995de566f86": {
        "name": "Kwajalein Atoll",
        "latitude": 9.0477206,
        "longitude": 167.7431292
    },

    "5e9e4501f509094ba4566f84": {
        "name": "CCSFS SLC 40",
        "latitude": 28.5618571,
        "longitude": -80.577366
    },

    "5e9e4502f509092b78566f87": {
        "name": "VAFB SLC 4E",
        "latitude": 34.632093,
        "longitude": -120.610829
    },

    "5e9e4502f509094188566f88": {
        "name": "KSC LC 39A",
        "latitude": 28.6080585,
        "longitude": -80.6039558
    }
}

In [32]:
launchpad_lookup["5e9e4501f509094ba4566f84"]

{'name': 'CCSFS SLC 40', 'latitude': 28.5618571, 'longitude': -80.577366}

In [6]:
# def getCoreData(data):
#     for core in data['cores']:
#             if core['core'] != None:
#                 response = requests.get("https://api.spacexdata.com/v4/cores/"+core['core']).json()
#                 Block.append(response['block'])
#                 ReusedCount.append(response['reuse_count'])
#                 Serial.append(response['serial'])
#             else:
#                 Block.append(None)
#                 ReusedCount.append(None)
#                 Serial.append(None)
#             Outcome.append(str(core['landing_success'])+' '+str(core['landing_type']))
#             Flights.append(core['flight'])
#             GridFins.append(core['gridfins'])
#             Reused.append(core['reused'])
#             Legs.append(core['legs'])
#             LandingPad.append(core['landpad'])

In [65]:
def getCoreData(data):
    for date in data['date']:
        if date in core_lookup:
            core = core_lookup[date]

            Outcome.append(core['Outcome'])
            Flights.append(core['Flights'])
            GridFins.append(core['GridFins'])
            Reused.append(core['Reused'])
            Legs.append(core['Legs'])
            LandingPad.append(core['LandingPad'])
            Block.append(core['Block'])
            ReusedCount.append(core['ReusedCount'])
            Serial.append(core['Serial'])

        else:
            Outcome.append(None)
            Flights.append(None)
            GridFins.append(None)
            Reused.append(None)
            Legs.append(None)
            LandingPad.append(None)
            Block.append(None)
            ReusedCount.append(None)
            Serial.append(None)

In [66]:
Outcome = []
Flights = []
GridFins = []
Reused = []
Legs = []
LandingPad = []
Block = []
ReusedCount = []
Serial = []

In [67]:
getCoreData(data)

In [68]:
print(len(data))
print(len(Outcome))
print(len(Flights))
print(len(GridFins))
print(len(Reused))
print(len(Legs))
print(len(LandingPad))
print(len(Block))
print(len(ReusedCount))
print(len(Serial))

107
107
107
107
107
107
107
107
107
107

In [63]:
core_lookup = fallback.set_index('Date')[
    ['Outcome', 'Flights', 'GridFins', 'Reused', 'Legs',
     'LandingPad', 'Block', 'ReusedCount', 'Serial']
].to_dict('index')

In [64]:
list(core_lookup.items())[:2]

[(datetime.date(2010, 6, 4),
  {'Outcome': 'None None',
   'Flights': 1,
   'GridFins': False,
   'Reused': False,
   'Legs': False,
   'LandingPad': nan,
   'Block': 1.0,
   'ReusedCount': 0,
   'Serial': 'B0003'}),
 (datetime.date(2012, 5, 22),
  {'Outcome': 'None None',
   'Flights': 1,
   'GridFins': False,
   'Reused': False,
   'Legs': False,
   'LandingPad': nan,
   'Block': 1.0,
   'ReusedCount': 0,
   'Serial': 'B0005'})]

In [7]:
spacex_url="https://api.spacexdata.com/v4/launches/past"

In [8]:
response = requests.get(spacex_url)

In [9]:
print(response.content)

b'<!DOCTYPE html>\n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->\n<head>\n\n<title>spacexdata.com | 525: SSL handshake failed</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />\n</head>\n<body>\n<div id="cf-wrapper">\n    <div id="cf-error-details" class="p-0">\n        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">\n            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">\n                <span class="inline-block">SSL handshake failed</span>\n                <span class="code-label">Error code 525</span>\n            </h1>\n            <div>\n                Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_525&utm_campaign=api.spacexdata.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.\n            </div>\n            <div class="mt-3">2026-10-04 06:06:43 UTC</div>\n        </header>\n        <div class="my-8 bg-gradient-gray">\n            <div class="w-240 lg:w-full mx-auto">\n                <div class="clearfix md:px-8">\n                    <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n  <div class="relative mb-10 md:m-0">\n    \n    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    \n  </div>\n  <span class="md:block w-full truncate">You</span>\n  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">\n  \n    Browser\n  \n  </h3>\n  \n  <span class="leading-1.3 text-2xl text-green-success">Working</span>\n  \n</div>\n                    <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n  <div class="relative mb-10 md:m-0">\n    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_525&#38;utm_campaign=api.spacexdata.com" target="_blank" rel="noopener noreferrer">\n    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    </a>\n  </div>\n  <span class="md:block w-full truncate">Ashburn</span>\n  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">\n  <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_525&utm_campaign=api.spacexdata.com" target="_blank" rel="noopener noreferrer">\n    Cloudflare\n  </a>\n  </h3>\n  \n  <span class="leading-1.3 text-2xl text-green-success">Working</span>\n  \n</div>\n                    <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">\n  <div class="relative mb-10 md:m-0">\n    \n    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>\n    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>\n    \n  </div>\n  <span class="md:block w-full truncate">api.spacexdata.com</span>\n  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">\n  \n    Host\n  \n  </h3>\n  \n  <span class="leading-1.3 text-2xl text-red-error">Error</span>\n  \n</div>\n                </div>\n            </div>\n        </div>\n\n        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">\n            <div class="clearfix">\n                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">\n                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>\n                    <p>The SSL/TLS handshake between Cloudflare and the origin web server failed.</p>\n                </div>\n                <div class="w-1/2 md:w-full float-left leading-relaxed">\n                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>\n                    \n                <h3 class="text-15 font-semibold mb-2">If you\'re a visitor of this website:</h3>\n                <p class="mb-6">Please try again in a few minutes.</p>\n\n                <h3 class="text-15 font-semibold mb-2">If you\'re the owner of this website:</h3>\n                <p>Please refer to the <a rel="noopener noreferrer" href="https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-525/">Error 525</a> article:</p>\n                <ul class="ml-4">\n                  <li>Verify a valid SSL certificate is installed on your origin server. If none exists, install a free <a rel="noopener noreferrer" href="https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/">Cloudflare Origin CA certificate</a>.</li>\n                  <li>Check <a rel="noopener noreferrer" href="https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-525/#diagnose-with-origin-analytics">Origin Analytics</a>.</li>\n                  <li>Ensure port 443 is open and your origin supports SNI.</li>\n                  <li>Review your server\'s <a rel="noopener noreferrer" href="https://developers.cloudflare.com/ssl/edge-certificates/additional-options/cipher-suites/">cipher suites</a> for compatibility with Cloudflare.</li>\n                </ul>\n                </div>\n            </div>\n        </div>\n\n        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n    <p class="text-13">\n      <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">a45200914e0bda5c</strong></span>\n      <span class="cf-footer-separator sm:hidden">&bull;</span>\n      <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">\n        Your IP:\n        <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>\n        <span class="hidden" id="cf-footer-ip">52.117.120.36</span>\n        <span class="cf-footer-separator sm:hidden">&bull;</span>\n      </span>\n      <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_525&#38;utm_campaign=api.spacexdata.com" id="brand_link" target="_blank">Cloudflare</a></span>\n      \n    </p>\n    <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>\n  </div><!-- /.error-footer -->\n\n    </div>\n</div>\n</body>\n</html>'

In [10]:
static_json_url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json'

In [15]:
response = requests.get(static_json_url)
print(response.status_code)

200

In [16]:
data = response.json()

In [17]:
data[0]

{'fairings': {'reused': False,
  'recovery_attempt': False,
  'recovered': False,
  'ships': []},
 'links': {'patch': {'small': 'https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png',
   'large': 'https://images2.imgbox.com/40/e3/GypSkayF_o.png'},
  'reddit': {'campaign': None,
   'launch': None,
   'media': None,
   'recovery': None},
  'flickr': {'small': [], 'original': []},
  'presskit': None,
  'webcast': 'https://www.youtube.com/watch?v=0a_00nJ_Y88',
  'youtube_id': '0a_00nJ_Y88',
  'article': 'https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html',
  'wikipedia': 'https://en.wikipedia.org/wiki/DemoSat'},
 'static_fire_date_utc': '2006-03-17T00:00:00.000Z',
 'static_fire_date_unix': 1142553600,
 'tbd': False,
 'net': False,
 'window': 0,
 'rocket': '5e9d0d95eda69955f709d1eb',
 'success': False,
 'details': 'Engine failure at 33 seconds and loss of vehicle',
 'crew': [],
 'ships': [],
 'capsules': [],
 'payloads': ['5eb0e4b5b6c3bb0006eeb1e1'],
 'launchpad': '5e9e4502f5090995de566f86',
 'auto_update': True,
 'failures': [{'time': 33,
   'altitude': None,
   'reason': 'merlin engine failure'}],
 'flight_number': 1,
 'name': 'FalconSat',
 'date_utc': '2006-03-24T22:30:00.000Z',
 'date_unix': 1143239400,
 'date_local': '2006-03-25T10:30:00+12:00',
 'date_precision': 'hour',
 'upcoming': False,
 'cores': [{'core': '5e9e289df35918033d3b2623',
   'flight': 1,
   'gridfins': False,
   'legs': False,
   'reused': False,
   'landing_attempt': False,
   'landing_success': None,
   'landing_type': None,
   'landpad': None}],
 'id': '5eb87cd9ffd86e000604b32a'}

In [18]:
data = pd.json_normalize(response.json())

In [19]:
data.head()

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,capsules,payloads,launchpad,auto_update,failures,flight_number,name,date_utc,date_unix,date_local,date_precision,upcoming,cores,id,fairings.reused,fairings.recovery_attempt,fairings.recovered,fairings.ships,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Engine failure at 33 seconds and loss of vehicle,[],[],[],[5eb0e4b5b6c3bb0006eeb1e1],5e9e4502f5090995de566f86,True,"[{'time': 33, 'altitude': None, 'reason': 'merlin engine failure'}]",1,FalconSat,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cd9ffd86e000604b32a,False,False,False,[],https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png,https://images2.imgbox.com/40/e3/GypSkayF_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html,https://en.wikipedia.org/wiki/DemoSat,NaN
1,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,"Successful first stage burn and transition to second stage, maximum altitude 289 km, Premature engine shutdown at T+7 min 30 s, Failed to reach orbit, Failed to recover first stage",[],[],[],[5eb0e4b6b6c3bb0006eeb1e2],5e9e4502f5090995de566f86,True,"[{'time': 301, 'altitude': 289, 'reason': 'harmonic oscillation leading to premature engine shutdown'}]",2,DemoSat,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdaffd86e000604b32b,False,False,False,[],https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png,https://images2.imgbox.com/be/e7/iNqsqVYM_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-rocket-fails-reach-orbit.html,https://en.wikipedia.org/wiki/DemoSat,NaN
2,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Residual stage 1 thrust led to collision between stage 1 and stage 2,[],[],[],"[5eb0e4b6b6c3bb0006eeb1e3, 5eb0e4b6b6c3bb0006eeb1e4]",5e9e4502f5090995de566f86,True,"[{'time': 140, 'altitude': 35, 'reason': 'residual stage-1 thrust led to collision between stage 1 and stage 2'}]",3,Trailblazer,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdbffd86e000604b32c,False,False,False,[],https://images2.imgbox.com/3d/86/cnu0pan8_o.png,https://images2.imgbox.com/4b/bd/d8UxLh4q_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1-flight-3-mission-summary,https://en.wikipedia.org/wiki/Trailblazer_(satellite),NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,True,"Ratsat was carried to orbit on the first successful orbital launch of any privately funded and developed, liquid-propelled carrier rocket, the SpaceX Falcon 1",[],[],[],[5eb0e4b7b6c3bb0006eeb1e5],5e9e4502f5090995de566f86,True,[],4,RatSat,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdbffd86e000604b32d,False,False,False,[],https://images2.imgbox.com/e9/c9/T8CfiSYb_o.png,https://images2.imgbox.com/e0/a7/FNjvKlXW_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,True,None,[],[],[],[5eb0e4b7b6c3bb0006eeb1e6],5e9e4502f5090995de566f86,True,[],5,RazakSat,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",5eb87cdcffd86e000604b32e,False,False,False,[],https://images2.imgbox.com/a7/ba/NBZSw3Ho_o.png,https://images2.imgbox.com/8d/fc/0qdZMWWx_o.png,None,None,None,None,[],[],http://www.spacex.com/press/2012/12/19/spacexs-falcon-1-successfully-delivers-razaksat-satellite-orbit,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1-flight-5,https://en.wikipedia.org/wiki/RazakSAT,NaN

In [20]:
getBoosterVersion(data)
getLaunchSite(data)
getPayloadData(data)
getCoreData(data)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)